### ISSUE TITLE
How to use PutFile Processor in Apache nifi  in Docker Container?

### ISSUE THREAD

**Issue by vsharathchandra** [sunileman/DockerNiFi#1]
I have used a simple flow given here https://github.com/xmlking/nifi-examples/tree/master/http-get-route .I am getting a "java.nio.file.AccessDeniedException" error in PutFile Processor.I guess it is beacause I am running nifi inside Docker.What Directory path should I pass to PutFIle ?

**Comment by katticot** [comment]
Hi,
if you use the [official](https://hub.docker.com/r/apache/nifi/) docker image.
Use the path /opt/nifi/nifi-1.7.1 , nifi-1.7.1 depends of your nifi version.
Or create a directory with write permission for the nifi user.

**Comment by ayushi4** [comment]
Hi,
I am using GetFile processor in nifi.  After creating directory I am getting 'Invalid directory as directory does not exist'. It is because I am running nifi inside Docker. But directory is present on my local machine.
What directory path should I pass to GetFile processor so that I can get files from my local machine?

**Comment by dalibor-sanzeru** [comment]
In docker-compose.yml under services sections when confoguring nifi you can bind directories within docker image with directories in host system. In following example **fileprocessor** is my **custom directory**. Nifi docker image has access to host directory -> means e.g. in GetFile processor this will be used for path **/opt/nifi/nifi-current/fileprocessor/**

```
    nifi:     
        image: apache/nifi:1.13.2
        container_name: nifi
        restart: always
        ports:
            - 8091:8080
        environment:
            - NIFI_WEB_HTTP_PORT = 8091
        volumes:
            - ./nifi/conf:/opt/nifi/nifi-current/conf
            - ./nifi/content:/opt/nifi/nifi-current/content_repository
            - ./nifi/db:/opt/nifi/nifi-current/database_repository
            - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
            - ./nifi/state:/opt/nifi/nifi-current/state
            - ./nifi/logs:/opt/nifi/nifi-current/logs
            - ./nifi/fileprocessor:/opt/nifi/nifi-current/fileprocessor
```
